# Site settings
title: Nu Documentation
email: development@nubits.com
description: > # this means to ignore newlines until "baseurl:"
  //TODO: Site description needs to be updated
baseurl: "/documentation/" # the subpath of your site, e.g. /blog/
url: "http://nunetwork.github.io" # the base hostname & protocol for your site
historyurl: https://github.com/NewNetwork/documentation/commits/gh-pages/_kb/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']

collections:
  kb:
    output: true
